apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookreview-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookreview
  template:
    metadata:
      labels:
        app: bookreview
    spec:
      containers:
      - name: bookreview
        image: bookreview:latest
        ports:
        - containerPort: 8080
